### ISSUE TITLE
publish as v0.1.0 on npm and bower

### ISSUE THREAD

**Issue by bjornstar** [devon-capital/dc-tabs#1]
First of all, thanks for taking the time to update this.

Could you publish this as v0.1.0 on npm and bower and add a tag for v0.1.0 on this repo?

I'd love to be able to use this without ember-cli. I can send you a PR if you don't have time or interest in doing the work.

**Comment by jrhe** [comment]
Hi bjornstar,

I will get to doing this later today or tomorrow. I don't have any projects which don't use ember-cli and don't have time atm so a PR would be great.

Cheers,

J

**Comment by jrhe** [comment]
Done.

Cheers,

J

**Comment by jrhe** [comment]
When you do that PR, I'll try and get it merged in as quickly as possible.
